/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as DatabasesIndexRouteImport } from './routes/databases.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DatabasesAddRouteImport } from './routes/databases.add'
import { Route as ApiPublicSiteConfigRouteImport } from './routes/api/public/site-config'
import { Route as ApiExternalSchemasMirrorRouteImport } from './routes/api.external-schemas.mirror'
import { Route as ApiExternalDataSyncRouteImport } from './routes/api.external-data.sync'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesIndexRoute = DatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesAddRoute = DatabasesAddRouteImport.update({
  id: '/databases/add',
  path: '/databases/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteConfigRoute = ApiPublicSiteConfigRouteImport.update({
  id: '/api/public/site-config',
  path: '/api/public/site-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalSchemasMirrorRoute =
  ApiExternalSchemasMirrorRouteImport.update({
    id: '/api/external-schemas/mirror',
    path: '/api/external-schemas/mirror',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExternalDataSyncRoute = ApiExternalDataSyncRouteImport.update({
  id: '/api/external-data/sync',
  path: '/api/external-data/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/databases/add': typeof DatabasesAddRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/databases/': typeof DatabasesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/external-data/sync': typeof ApiExternalDataSyncRoute
  '/api/external-schemas/mirror': typeof ApiExternalSchemasMirrorRoute
  '/api/public/site-config': typeof ApiPublicSiteConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/databases/add': typeof DatabasesAddRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/databases': typeof DatabasesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/external-data/sync': typeof ApiExternalDataSyncRoute
  '/api/external-schemas/mirror': typeof ApiExternalSchemasMirrorRoute
  '/api/public/site-config': typeof ApiPublicSiteConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/connections': typeof ConnectionsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/databases/add': typeof DatabasesAddRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/databases/': typeof DatabasesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/external-data/sync': typeof ApiExternalDataSyncRoute
  '/api/external-schemas/mirror': typeof ApiExternalSchemasMirrorRoute
  '/api/public/site-config': typeof ApiPublicSiteConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/apps'
    | '/auth'
    | '/backups'
    | '/connections'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/health'
    | '/logs'
    | '/pricing'
    | '/sitemap.xml'
    | '/websites'
    | '/databases/add'
    | '/projects/$projectId'
    | '/databases/'
    | '/projects/'
    | '/api/external-data/sync'
    | '/api/external-schemas/mirror'
    | '/api/public/site-config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/apps'
    | '/auth'
    | '/backups'
    | '/connections'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/health'
    | '/logs'
    | '/pricing'
    | '/sitemap.xml'
    | '/websites'
    | '/databases/add'
    | '/projects/$projectId'
    | '/databases'
    | '/projects'
    | '/api/external-data/sync'
    | '/api/external-schemas/mirror'
    | '/api/public/site-config'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/apps'
    | '/auth'
    | '/backups'
    | '/connections'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/health'
    | '/logs'
    | '/pricing'
    | '/sitemap.xml'
    | '/websites'
    | '/databases/add'
    | '/projects/$projectId'
    | '/databases/'
    | '/projects/'
    | '/api/external-data/sync'
    | '/api/external-schemas/mirror'
    | '/api/public/site-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  BackupsRoute: typeof BackupsRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  HealthRoute: typeof HealthRoute
  LogsRoute: typeof LogsRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WebsitesRoute: typeof WebsitesRoute
  DatabasesAddRoute: typeof DatabasesAddRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  DatabasesIndexRoute: typeof DatabasesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiExternalDataSyncRoute: typeof ApiExternalDataSyncRoute
  ApiExternalSchemasMirrorRoute: typeof ApiExternalSchemasMirrorRoute
  ApiPublicSiteConfigRoute: typeof ApiPublicSiteConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof DatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/add': {
      id: '/databases/add'
      path: '/databases/add'
      fullPath: '/databases/add'
      preLoaderRoute: typeof DatabasesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-config': {
      id: '/api/public/site-config'
      path: '/api/public/site-config'
      fullPath: '/api/public/site-config'
      preLoaderRoute: typeof ApiPublicSiteConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-schemas/mirror': {
      id: '/api/external-schemas/mirror'
      path: '/api/external-schemas/mirror'
      fullPath: '/api/external-schemas/mirror'
      preLoaderRoute: typeof ApiExternalSchemasMirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-data/sync': {
      id: '/api/external-data/sync'
      path: '/api/external-data/sync'
      fullPath: '/api/external-data/sync'
      preLoaderRoute: typeof ApiExternalDataSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  BackupsRoute: BackupsRoute,
  ConnectionsRoute: ConnectionsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  HealthRoute: HealthRoute,
  LogsRoute: LogsRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WebsitesRoute: WebsitesRoute,
  DatabasesAddRoute: DatabasesAddRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  DatabasesIndexRoute: DatabasesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiExternalDataSyncRoute: ApiExternalDataSyncRoute,
  ApiExternalSchemasMirrorRoute: ApiExternalSchemasMirrorRoute,
  ApiPublicSiteConfigRoute: ApiPublicSiteConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
