/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatabasesIndexRouteImport } from './routes/databases.index'
import { Route as DatabasesAddRouteImport } from './routes/databases.add'
import { Route as ApiPublicSiteConfigRouteImport } from './routes/api/public/site-config'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesIndexRoute = DatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesAddRoute = DatabasesAddRouteImport.update({
  id: '/databases/add',
  path: '/databases/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteConfigRoute = ApiPublicSiteConfigRouteImport.update({
  id: '/api/public/site-config',
  path: '/api/public/site-config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/connections': typeof ConnectionsRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/databases/add': typeof DatabasesAddRoute
  '/databases/': typeof DatabasesIndexRoute
  '/api/public/site-config': typeof ApiPublicSiteConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/connections': typeof ConnectionsRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/databases/add': typeof DatabasesAddRoute
  '/databases': typeof DatabasesIndexRoute
  '/api/public/site-config': typeof ApiPublicSiteConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/backups': typeof BackupsRoute
  '/connections': typeof ConnectionsRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/websites': typeof WebsitesRoute
  '/databases/add': typeof DatabasesAddRoute
  '/databases/': typeof DatabasesIndexRoute
  '/api/public/site-config': typeof ApiPublicSiteConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/apps'
    | '/auth'
    | '/backups'
    | '/connections'
    | '/health'
    | '/logs'
    | '/sitemap.xml'
    | '/websites'
    | '/databases/add'
    | '/databases/'
    | '/api/public/site-config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/apps'
    | '/auth'
    | '/backups'
    | '/connections'
    | '/health'
    | '/logs'
    | '/sitemap.xml'
    | '/websites'
    | '/databases/add'
    | '/databases'
    | '/api/public/site-config'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/apps'
    | '/auth'
    | '/backups'
    | '/connections'
    | '/health'
    | '/logs'
    | '/sitemap.xml'
    | '/websites'
    | '/databases/add'
    | '/databases/'
    | '/api/public/site-config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  BackupsRoute: typeof BackupsRoute
  ConnectionsRoute: typeof ConnectionsRoute
  HealthRoute: typeof HealthRoute
  LogsRoute: typeof LogsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WebsitesRoute: typeof WebsitesRoute
  DatabasesAddRoute: typeof DatabasesAddRoute
  DatabasesIndexRoute: typeof DatabasesIndexRoute
  ApiPublicSiteConfigRoute: typeof ApiPublicSiteConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/': {
      id: '/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof DatabasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/add': {
      id: '/databases/add'
      path: '/databases/add'
      fullPath: '/databases/add'
      preLoaderRoute: typeof DatabasesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-config': {
      id: '/api/public/site-config'
      path: '/api/public/site-config'
      fullPath: '/api/public/site-config'
      preLoaderRoute: typeof ApiPublicSiteConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  BackupsRoute: BackupsRoute,
  ConnectionsRoute: ConnectionsRoute,
  HealthRoute: HealthRoute,
  LogsRoute: LogsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WebsitesRoute: WebsitesRoute,
  DatabasesAddRoute: DatabasesAddRoute,
  DatabasesIndexRoute: DatabasesIndexRoute,
  ApiPublicSiteConfigRoute: ApiPublicSiteConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
